import { Settings, Plus, Building2, Truck, MapPin, Package, Wrench, BarChart3 } from 'lucide-react';
import type { ModuleTilesConfig } from '../../types/tiles';

export const adminTiles: ModuleTilesConfig = {
  moduleId: 'administracion',
  moduleName: 'Administración',
  icon: Settings,
  breadcrumb: ['Administración', 'Inicio'],
  subtitle: 'Gestión de sedes, vehículos, zonas y materiales',
  categories: [
    {
      id: 'acciones',
      title: 'Acciones',
      tiles: [
        {
          id: 'nueva-sede',
          icon: Plus,
          title: 'Nueva Sede',
          description: 'Registrar sucursal o sede',
          path: '/dashboard/sedes?action=create',
          permission: 'sedes:leer',
          type: 'action',
        },
        {
          id: 'nuevo-vehiculo',
          icon: Plus,
          title: 'Nuevo Vehículo',
          description: 'Registrar vehículo',
          path: '/dashboard/vehiculos?action=create',
          permission: 'vehiculos:leer',
          type: 'action',
        },
        {
          id: 'nueva-zona',
          icon: Plus,
          title: 'Nueva Zona',
          description: 'Crear zona geográfica',
          path: '/dashboard/zonas?action=create',
          permission: 'zonas:leer',
          type: 'action',
        },
        {
          id: 'nuevo-material',
          icon: Plus,
          title: 'Nuevo Material',
          description: 'Agregar material',
          path: '/dashboard/materiales?action=create',
          permission: 'materiales:leer',
          type: 'action',
        },
      ],
    },
    {
      id: 'consultas',
      title: 'Consultas',
      tiles: [
        {
          id: 'sedes',
          icon: Building2,
          title: 'Sedes',
          description: 'Gestionar sucursales',
          path: '/dashboard/sedes',
          permission: 'sedes:leer',
          type: 'query',
        },
        {
          id: 'vehiculos',
          icon: Truck,
          title: 'Vehículos',
          description: 'Flota de vehículos',
          path: '/dashboard/vehiculos',
          permission: 'vehiculos:leer',
          type: 'query',
        },
        {
          id: 'zonas',
          icon: MapPin,
          title: 'Zonas',
          description: 'Zonas geográficas',
          path: '/dashboard/zonas',
          permission: 'zonas:leer',
          type: 'query',
        },
        {
          id: 'materiales',
          icon: Package,
          title: 'Materiales',
          description: 'Catálogo de materiales',
          path: '/dashboard/materiales',
          permission: 'materiales:leer',
          type: 'query',
        },
      ],
    },
    {
      id: 'reportes',
      title: 'Reportes',
      tiles: [
        {
          id: 'mantenimiento-vehiculos',
          icon: Wrench,
          title: 'Mantenimiento',
          description: 'Vehículos en taller',
          path: '/dashboard/vehiculos?estado=TALLER',
          permission: 'vehiculos:leer',
          type: 'report',
        },
        {
          id: 'estadisticas',
          icon: BarChart3,
          title: 'Estadísticas',
          description: 'Métricas generales',
          path: '/dashboard/vehiculos?tab=estadisticas',
          permission: 'vehiculos:leer',
          type: 'report',
        },
      ],
    },
  ],
};
