import {
  ClipboardList,
  Plus,
  Clock,
  HardHat,
  AlertCircle,
  CheckCircle,
  BarChart3,
  Users,
} from 'lucide-react';
import type { ModuleTilesConfig } from '../../types/tiles';

export const operacionesTiles: ModuleTilesConfig = {
  moduleId: 'operaciones',
  moduleName: 'Operaciones',
  icon: ClipboardList,
  breadcrumb: ['Operaciones', 'Inicio'],
  subtitle: 'Gestión de tickets y obras',
  categories: [
    {
      id: 'acciones',
      title: 'Acciones',
      tiles: [
        {
          id: 'nuevo-ticket',
          icon: Plus,
          title: 'Nuevo Ticket',
          description: 'Crear solicitud de servicio',
          path: '/dashboard/tickets?action=create',
          permission: 'tickets:escribir',
          type: 'action',
        },
        {
          id: 'nueva-obra',
          icon: HardHat,
          title: 'Nueva Obra',
          description: 'Registrar obra o proyecto',
          path: '/dashboard/obras?action=create',
          permission: 'obras:escribir',
          type: 'action',
        },
      ],
    },
    {
      id: 'consultas',
      title: 'Consultas',
      tiles: [
        {
          id: 'todos-tickets',
          icon: ClipboardList,
          title: 'Todos los Tickets',
          description: 'Ver listado completo',
          path: '/dashboard/tickets',
          permission: 'tickets:leer',
          type: 'query',
        },
        {
          id: 'tickets-pendientes',
          icon: Clock,
          title: 'Tickets Pendientes',
          description: 'Sin asignar o en progreso',
          path: '/dashboard/tickets?estado=ABIERTO,EN_PROGRESO',
          permission: 'tickets:leer',
          type: 'query',
        },
        {
          id: 'tickets-urgentes',
          icon: AlertCircle,
          title: 'Urgentes',
          description: 'Tickets de alta prioridad',
          path: '/dashboard/tickets?prioridad=URGENTE',
          permission: 'tickets:leer',
          type: 'query',
        },
        {
          id: 'tickets-cerrados',
          icon: CheckCircle,
          title: 'Tickets Cerrados',
          description: 'Tickets finalizados',
          path: '/dashboard/tickets?estado=CERRADO',
          permission: 'tickets:leer',
          type: 'query',
        },
        {
          id: 'todas-obras',
          icon: HardHat,
          title: 'Todas las Obras',
          description: 'Ver obras y proyectos',
          path: '/dashboard/obras',
          permission: 'obras:leer',
          type: 'query',
        },
        {
          id: 'mis-tickets',
          icon: Users,
          title: 'Mis Tickets',
          description: 'Tickets asignados a mí',
          path: '/dashboard/tickets?asignadoAMi=true',
          permission: 'tickets:leer',
          type: 'query',
        },
      ],
    },
    {
      id: 'reportes',
      title: 'Reportes',
      tiles: [
        {
          id: 'reporte-tickets',
          icon: BarChart3,
          title: 'Dashboard Tickets',
          description: 'Métricas y estadísticas',
          path: '/dashboard',
          permission: 'tickets:leer',
          type: 'report',
        },
      ],
    },
  ],
};
