import {
  Wallet,
  Plus,
  ArrowLeftRight,
  Landmark,
  CreditCard,
  Receipt,
  History,
  BarChart3,
  FileText,
  TrendingUp,
} from 'lucide-react';
import type { ModuleTilesConfig } from '../../types/tiles';

export const tesoreriaTiles: ModuleTilesConfig = {
  moduleId: 'tesoreria',
  moduleName: 'Tesorería',
  icon: Wallet,
  breadcrumb: ['Tesorería', 'Inicio'],
  subtitle: 'Gestión de caja, bancos y movimientos financieros',
  categories: [
    {
      id: 'acciones',
      title: 'Acciones Rápidas',
      tiles: [
        {
          id: 'nuevo-movimiento',
          icon: Plus,
          title: 'Nuevo Movimiento',
          description: 'Registrar ingreso o egreso',
          path: '/dashboard/finanzas/movimientos?action=create',
          permission: 'finanzas:escribir',
          type: 'action',
        },
        {
          id: 'nueva-transferencia',
          icon: ArrowLeftRight,
          title: 'Transferencia',
          description: 'Mover fondos entre cuentas',
          path: '/dashboard/finanzas/movimientos?tipo=TRANSFERENCIA',
          permission: 'finanzas:escribir',
          type: 'action',
        },
        {
          id: 'nueva-cuenta',
          icon: Landmark,
          title: 'Nueva Cuenta',
          description: 'Crear cuenta bancaria',
          path: '/dashboard/finanzas/cuentas?action=create',
          permission: 'finanzas:escribir',
          type: 'action',
        },
        {
          id: 'nuevo-gasto-tarjeta',
          icon: CreditCard,
          title: 'Registrar Gasto',
          description: 'Gasto con tarjeta',
          path: '/dashboard/rendiciones',
          permission: 'tarjetas:escribir',
          type: 'action',
        },
      ],
    },
    {
      id: 'consultas',
      title: 'Consultas',
      tiles: [
        {
          id: 'dashboard-finanzas',
          icon: BarChart3,
          title: 'Dashboard Financiero',
          description: 'Ver métricas y gráficos',
          path: '/dashboard/finanzas',
          permission: 'finanzas:leer',
          type: 'query',
        },
        {
          id: 'ver-cuentas',
          icon: Landmark,
          title: 'Cuentas y Bancos',
          description: 'Gestionar cuentas bancarias',
          path: '/dashboard/finanzas/cuentas',
          permission: 'finanzas:leer',
          type: 'query',
        },
        {
          id: 'ver-movimientos',
          icon: History,
          title: 'Movimientos',
          description: 'Historial de transacciones',
          path: '/dashboard/finanzas/movimientos',
          permission: 'finanzas:leer',
          type: 'query',
        },
        {
          id: 'ver-tarjetas',
          icon: CreditCard,
          title: 'Tarjetas',
          description: 'Gestionar tarjetas',
          path: '/dashboard/finanzas/tarjetas',
          permission: 'tarjetas:leer',
          type: 'query',
        },
        {
          id: 'mis-gastos',
          icon: Receipt,
          title: 'Mis Gastos',
          description: 'Ver y rendir gastos',
          path: '/dashboard/rendiciones',
          permission: 'tarjetas:leer',
          type: 'query',
        },
      ],
    },
    {
      id: 'reportes',
      title: 'Reportes',
      tiles: [
        {
          id: 'flujo-caja',
          icon: TrendingUp,
          title: 'Flujo de Caja',
          description: 'Análisis de ingresos y egresos',
          path: '/dashboard/finanzas?tab=flujo',
          permission: 'finanzas:leer',
          type: 'report',
        },
        {
          id: 'conciliacion',
          icon: FileText,
          title: 'Conciliación',
          description: 'Conciliar movimientos',
          path: '/dashboard/finanzas/movimientos?estado=CONFIRMADO',
          permission: 'finanzas:leer',
          type: 'report',
        },
      ],
    },
  ],
};
